services:
  flask-app:
    build: ./site
    container_name: flask-app
    environment:
      - FLASK_ENV=development #устранить при проде
      - PYTHONUNBUFFERED=True  
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD
    restart: always
    volumes:
      - ./site:/site
    ports:
      - "5000:5000"
    command: python app.py
    depends_on:
      - rabbitmq

  telegram-bot:
    build: ./bot
    container_name: telegram-bot
    restart: always
    environment:
      - BOT_TOKEN
      - PASSWORD
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD
    command: python aiogram_run.py
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
