services:
  flask-app:
    build: ./site
    container_name: flask-app
    environment:
      - PYTHONUNBUFFERED=True
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD
      - FLASK_ENV=production
    restart: always
    volumes:
      - ./site:/site
    ports:
      - "5000:5000"
    command: gunicorn -w 1 -b 0.0.0.0:5000 app:app
    depends_on:
      - rabbitmq
    logging:
      driver: "none"

  telegram-bot:
    build: ./bot
    container_name: telegram-bot
    restart: always
    environment:
      - BOT_TOKEN
      - PASSWORD
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD
    command: python aiogram_run.py
    volumes:
      - ./bot:/bot
    depends_on:
      - rabbitmq
    logging:
      driver: "none"

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    restart: always
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      driver: "none"
